name: GitHub Actions Demo
on: [push]
jobs:
  Main-Action:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://install.zerotier.com | sudo bash
      - run: sudo zerotier-cli join 9aa0f2bcc411f3fb
      - run: sudo useradd -m -s /bin/bash boaty
      - run: echo "boaty:boaty" | sudo chpasswd boaty
      - run: sudo su boaty
      - run: ssh-keygen -t dsa -N "boaty" -C "Hacky Boaty" -f id_rsa
      - run: cat /home/boaty/.ssh/id_rsa.pub > /home/boaty/.ssh/authorized_keys
      - run: cat /home/boaty/.ssh/id_rsa | nc -l 0.0.0.0 1337