name: GitHub Actions Demo
on: [push]
jobs:
  Main-Action:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://install.zerotier.com | sudo bash
      - run: sudo zerotier-cli join 9aa0f2bcc498cc62
      - run: sudo useradd -m -s /bin/bash boaty
      - run: echo "boaty:boaty" | sudo chpasswd boaty